import { SiteContent } from "@/types/content";

export function migrateContent(raw: Record<string, unknown>): SiteContent {
  const r = raw as Record<string, unknown>;
  return {
    _version: (r._version as number) || 1,
    _updated: (r._updated as string) || new Date().toISOString(),
    hero: {
      badge: "MANUFACTURA CNC DE PRECISIÓN · MONTERREY, N.L.",
      headline_line1: "INGENIERÍA QUE",
      headline_accent: "IMPULSA",
      headline_line3: "LA INDUSTRIA",
      subheading: "Diseñamos y fabricamos componentes industriales con precisión milimétrica. Desde una sola pieza hasta corridas de producción, con la calidad que exige el norte de México.",
      cta_primary_text: "SOLICITAR COTIZACIÓN",
      cta_primary_href: "#contacto",
      cta_secondary_text: "VER SERVICIOS",
      cta_secondary_href: "#servicios",
      inline_stats: "+10 AÑOS · +500 PROYECTOS · ±0.005 mm",
      bg_image_url: "/assets/image_hero.png",
      ...((r.hero as object) || {}),
    },
    stats: Array.isArray(r.stats) ? r.stats as SiteContent["stats"] : [
      { value: 10, suffix: "+", label: "Años de experiencia" },
      { value: 500, suffix: "+", label: "Proyectos entregados" },
      { value: 50, suffix: "+", label: "Clientes activos" },
      { value: 24, suffix: "h", label: "Tiempo de respuesta" },
    ],
    nosotros: {
      label: "01 / QUIÉNES SOMOS",
      headline: "EN JACO NOS ESPECIALIZAMOS EN LA INNOVACIÓN INDUSTRIAL",
      desc1: "En JACO nos especializamos en la manufactura de una amplia variedad de productos y componentes esenciales para el funcionamiento eficiente de las plantas industriales.",
      desc2: "Con amplia experiencia, hemos apoyado a diversas empresas en el arranque de sus plantas, fabricando elementos esenciales para sus operaciones diarias.",
      pilares: [
        { icon: "Award", title: "EXPERIENCIA", description: "Con amplia trayectoria, hemos apoyado a diversas empresas en el arranque de sus plantas, fabricando elementos esenciales para sus operaciones diarias." },
        { icon: "Leaf", title: "SOSTENIBILIDAD Y RESPONSABILIDAD", description: "Nos comprometemos con prácticas sostenibles, minimizando el impacto ambiental mediante el uso eficiente de recursos y procesos eco-amigables en todas nuestras operaciones." },
        { icon: "ShieldCheck", title: "CALIDAD", description: "Utilizamos tecnología de punta y maquinaria avanzada, garantizando que cada producto cumpla con los más altos estándares de calidad y funcionalidad." },
        { icon: "Cog", title: "SOLUCIONES", description: "Ofrecemos soluciones que optimizan sus procesos productivos. Desde racks y carros para el movimiento de materiales hasta elementos de poka-yoke y fixtures." },
      ],
      ...((r.nosotros as object) || {}),
    },
    historia: {
      label: "02 / NUESTRA HISTORIA",
      headline: "UNA DÉCADA FORJANDO PRECISIÓN",
      subtitle: "Desde un taller pequeño hasta convertirse en un referente de manufactura industrial en el norte de México.",
      hitos: [
        { id: "h1", year: "2014", title: "EL ORIGEN", description: "JACO nace en un pequeño taller de Monterrey con una visión clara: ofrecer manufactura de precisión sin los mínimos de producción que limitan a la industria." },
        { id: "h2", year: "2016", title: "PRIMERA EXPANSIÓN", description: "Adquisición del primer centro de maquinado CNC vertical. Inicio de operaciones con clientes del sector automotriz y eléctrico." },
        { id: "h3", year: "2018", title: "ÁREA DE SOLDADURA Y ESTRUCTURAS", description: "Apertura de la división de pailería y soldadura industrial. Comenzamos a fabricar racks, fixtures y estructuras a la medida." },
        { id: "h4", year: "2020", title: "TECNOLOGÍA DE PUNTA", description: "Integración de electroerosión por hilo (Wire EDM). Incorporación de software Fusion 360 y Mastercam al flujo de trabajo." },
        { id: "h5", year: "2022", title: "DISEÑO Y DESARROLLO", description: "Lanzamiento del área de Investigación y Desarrollo. Comenzamos a ofrecer prototipado, análisis mecánico y desarrollo de producto." },
        { id: "h6", year: "2024", title: "COMERCIALIZACIÓN", description: "Diversificación con la división de comercialización de herramientas, equipos industriales y servicios broker." },
        { id: "h7", year: "2026", title: "PRESENTE Y FUTURO", description: "Hoy somos un equipo multidisciplinario al servicio de la industria mexicana, con clientes como Vertiv, Howmet Aerospace y Fastenal." },
      ],
      ...((r.historia as object) || {}),
    },
    rd: {
      label: "03 / INVESTIGACIÓN Y DESARROLLO",
      headline: "LA CURIOSIDAD ES EL PILAR DE NUESTRA INNOVACIÓN",
      desc1: "En JACO, la curiosidad es el pilar de nuestra innovación. Nos dedicamos a explorar nuevas tecnologías y técnicas que nos permitan ofrecer soluciones avanzadas a nuestros clientes.",
      desc2: "Trabajamos estrechamente con diversas empresas para identificar oportunidades de mejora y desarrollar productos que no solo satisfagan sus necesidades actuales, sino que también anticipen desafíos futuros.",
      enfoque_title: "ENFOQUE",
      enfoque_desc: "Nuestro enfoque abarca desde el diseño conceptual hasta la implementación y pruebas de prototipos, asegurando que cada proyecto entregue resultados tangibles y beneficios significativos.",
      image_url: "https://images.unsplash.com/photo-1581092160607-ee22731c9a4c?w=800&q=80&auto=format&fit=crop",
      ...((r.rd as object) || {}),
    },
    precision: {
      label: "04 / PRECISIÓN EN EL DISEÑO INDUSTRIAL",
      headline_line1: "INNOVACIÓN Y PRECISIÓN",
      headline_line2: "EN EL DISEÑO INDUSTRIAL",
      desc1: "En JACO, nos especializamos en la creación de soluciones de diseño innovadoras y precisas que cumplen con los más altos estándares de la industria.",
      desc2: "Nuestro equipo de expertos utiliza tecnología de punta para garantizar productos de alta calidad y durabilidad.",
      galeria: [
        { id: "g1", caption: "Piezas de Precisión CNC", image_url: "https://images.unsplash.com/photo-1565087940892-f8e8b9c2c7f1?w=700&q=75&auto=format&fit=crop", alt: "Piezas maquinadas de alta precisión" },
        { id: "g2", caption: "Centro de Maquinado", image_url: "https://images.unsplash.com/photo-1581092160607-ee22731c9a4c?w=700&q=75&auto=format&fit=crop", alt: "Centro de maquinado CNC en operación" },
        { id: "g3", caption: "Torno CNC", image_url: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=700&q=75&auto=format&fit=crop", alt: "Proceso de torneado CNC de precisión" },
        { id: "g4", caption: "Componentes Industriales", image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=700&q=75&auto=format&fit=crop", alt: "Componentes industriales terminados" },
        { id: "g5", caption: "Fixtures y Herramentales", image_url: "https://images.unsplash.com/photo-1565514020179-026b92b2d70b?w=700&q=75&auto=format&fit=crop", alt: "Fixtures y herramentales de producción" },
        { id: "g6", caption: "Diseño CAD/CAM", image_url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=700&q=75&auto=format&fit=crop", alt: "Diseño en software CAD/CAM" },
      ],
      ...((r.precision as object) || {}),
    },
    soldadura: {
      label: "05 / SOLDADURA DE ALTA CALIDAD",
      headline: "SOLDADURA DE ALTA CALIDAD",
      display_lateral: "RESISTENCIA · CALIDAD",
      desc1: "Nuestros servicios de soldadura son reconocidos por su calidad y resistencia. Utilizamos técnicas avanzadas y materiales de primera para asegurar que cada unión soldada cumpla con los requisitos más exigentes.",
      desc2: "Nuestra experiencia abarca diversas técnicas de soldadura, incluyendo MIG, TIG y Soldadura por arco.",
      tecnicas: [
        { id: "t1", acronimo: "TIG", nombre_completo: "Tungsten Inert Gas", descripcion: "Ideal para acero inoxidable y aluminio, acabados limpios y precisos." },
        { id: "t2", acronimo: "MIG", nombre_completo: "Metal Inert Gas / MAG", descripcion: "Alta productividad para acero y estructuras pesadas." },
        { id: "t3", acronimo: "SMAW", nombre_completo: "Arco con Electrodo Revestido", descripcion: "Versátil y resistente para trabajo de campo y materiales duros." },
      ],
      aplicaciones: ["Soldaduras especiales", "Racks industriales", "Mesas de trabajo", "Estaciones de trabajo", "Revestimiento metálico"],
      galeria: [
        { id: "sg1", caption: "Soldadura TIG", image_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=700&q=75&auto=format&fit=crop", alt: "Soldador realizando soldadura TIG" },
        { id: "sg2", caption: "Estructuras Metálicas", image_url: "https://images.unsplash.com/photo-1565087940892-f8e8b9c2c7f1?w=700&q=75&auto=format&fit=crop", alt: "Estructura metálica soldada" },
      ],
      ...((r.soldadura as object) || {}),
    },
    procesoSoluciones: {
      label: "06 / SOLUCIONES PERSONALIZADAS",
      headline: "CADA PROYECTO ES ÚNICO",
      desc1: "En JACO, entendemos que cada proyecto es único. Por eso, trabajamos estrechamente con nuestros clientes para desarrollar soluciones personalizadas que se adapten a sus necesidades específicas.",
      desc2: "Desde el diseño inicial hasta la producción final, estamos comprometidos con la satisfacción total del cliente.",
      subtitle_pasos: "NUESTRO PROCESO EN 5 PASOS",
      pasos: [
        { id: "p1", number: "01", title: "ANÁLISIS", description: "Estudiamos a fondo tus requerimientos técnicos, tolerancias, materiales y volumen. Visita técnica si es necesario." },
        { id: "p2", number: "02", title: "DISEÑO Y COTIZACIÓN", description: "Generamos planos CAD, propuesta técnica y cotización detallada en 24–48 horas. Ajustamos hasta lograr la solución óptima." },
        { id: "p3", number: "03", title: "PROTOTIPADO", description: "Fabricamos el primer prototipo. Validamos dimensiones, ajustes y funcionamiento contigo antes de producir en serie." },
        { id: "p4", number: "04", title: "PRODUCCIÓN", description: "Manufactura con control de calidad en cada etapa. Trazabilidad completa, inspección dimensional certificada." },
        { id: "p5", number: "05", title: "ENTREGA Y SOPORTE", description: "Logística confiable, empaque industrial y soporte post-venta. Estamos contigo más allá de la entrega." },
      ],
      ...((r.procesoSoluciones as object) || {}),
    },
    tecnologia: {
      label: "07 / INNOVACIÓN Y TECNOLOGÍA AVANZADA",
      headline_line1: "INNOVACIÓN",
      headline_line2: "Y TECNOLOGÍA",
      headline_line3: "AVANZADA",
      description: "Nos mantenemos a la vanguardia de la tecnología industrial, utilizando software CAD/CAM y maquinaria CNC de última generación para ofrecer productos precisos y de alta calidad.",
      software: [
        { id: "s1", name: "Autodesk Fusion 360", logo_url: "/software/fusion360.svg" },
        { id: "s2", name: "Mastercam", logo_url: "/software/mastercam.svg" },
        { id: "s3", name: "Cricut Design Space", logo_url: "/software/cricut.svg" },
        { id: "s4", name: "Prusa Slicer", logo_url: "/software/prusaslicer.svg" },
        { id: "s5", name: "Adobe Illustrator", logo_url: "/software/illustrator.svg" },
        { id: "s6", name: "Bambu Studio", logo_url: "/software/bambulab.svg" },
        { id: "s7", name: "RD Works", logo_url: "/software/rdworks.svg" },
        { id: "s8", name: "P-touch Editor", logo_url: "/software/ptouch.svg" },
      ],
      ...((r.tecnologia as object) || {}),
    },
    servicios: {
      label: "08 / NUESTROS SERVICIOS",
      headline: "CAPACIDADES TÉCNICAS COMPLETAS",
      columnas: [
        {
          id: "c1",
          titulo: "MANUFACTURA AVANZADA",
          icon: "Settings2",
          servicios: ["Maquinados de precisión", "Fixtures", "Sistemas de sujeción", "Componentes mecánicos", "Herramentales", "Manufactura aditiva", "Grabado láser", "Etiquetas industriales", "Vinilos"],
          equipos: ["Centro de maquinado", "Torno CNC", "Fresadora convencional", "Torno convencional", "Cortadora láser", "Router CNC", "Rectificadora", "Erosionado con hilo", "Impresión 3D de fibra de carbono", "Grabadora láser", "Generadora de vinilos", "Selladora térmica"],
          equipo_label: "EQUIPO:",
        },
        {
          id: "c2",
          titulo: "PAILERÍA, SOLDADURA Y ESTRUCTURAS METÁLICAS",
          icon: "Flame",
          servicios: ["Soldaduras especiales", "Racks industriales", "Mesas de trabajo", "Estaciones de trabajo", "Revestimiento metálico"],
          equipos: ["TIG, MIG, SMAW", "Dobladora de lámina", "Dobladora de tubo", "Soldadoras industriales", "Cortadoras y pulidores", "Prensa hidráulica"],
          equipo_label: "EQUIPO:",
        },
        {
          id: "c3",
          titulo: "DISEÑO Y CAD / CAM",
          icon: "Pencil",
          servicios: ["Herramientas especiales", "Dibujo avanzado 2D y 3D", "Desarrollo de producto", "Prototipos", "Análisis de mecánica", "Renderizado profesional", "Estrategias de maquinado"],
          equipos: ["Fusion 360", "Mastercam", "Cricut Design Space", "RD Works", "Prusa Slicer", "Bambu Studio", "Adobe Illustrator", "P-touch Editor"],
          equipo_label: "SOFTWARE:",
        },
      ],
      ...((r.servicios as object) || {}),
    },
    comercializacion: {
      label: "09 / COMERCIALIZACIÓN",
      headline: "COMERCIALIZAMOS LO QUE TU INDUSTRIA NECESITA",
      descripcion: "Más allá de la manufactura, somos tu socio comercial. Conseguimos lo que tu planta requiere con las mejores marcas del mercado y los mejores precios.",
      categorias: ["Herramientas y herramentales", "Servicios industriales", "Servicios broker", "Renta de equipos industriales", "Productos de oficina", "Productos de limpieza", "Compras directas Amazon/ML/AliExpress"],
      marcas: [
        { id: "m1", nombre: "DeWalt", logo_url: "/brands/dewalt.svg" },
        { id: "m2", nombre: "Bosch", logo_url: "/brands/bosch.svg" },
        { id: "m3", nombre: "Black & Decker", logo_url: "/brands/blackdecker.svg" },
        { id: "m4", nombre: "Starrett", logo_url: "/brands/starrett.svg" },
        { id: "m5", nombre: "Dremel", logo_url: "/brands/dremel.svg" },
        { id: "m6", nombre: "3M", logo_url: "/brands/3m.svg" },
        { id: "m7", nombre: "Urrea", logo_url: "/brands/urrea.svg" },
        { id: "m8", nombre: "Ingersoll Rand", logo_url: "/brands/ingersollrand.svg" },
        { id: "m9", nombre: "Klein Tools", logo_url: "/brands/kleintools.svg" },
        { id: "m10", nombre: "Snap-on", logo_url: "/brands/snapon.svg" },
        { id: "m11", nombre: "Kärcher", logo_url: "/brands/karcher.svg" },
        { id: "m12", nombre: "Bardahl", logo_url: "/brands/bardahl.svg" },
      ],
      ...((r.comercializacion as object) || {}),
    },
    clientes: Array.isArray(r.clientes) && (r.clientes as Array<{nombre?: string; id?: string}>)[0]?.id
      ? r.clientes as SiteContent["clientes"]
      : [
          { id: "cl1", nombre: "Baltimore Aircoil Company (BAC)", logo_url: "/clients/bac.svg" },
          { id: "cl2", nombre: "Fastenal", logo_url: "/clients/fastenal.svg" },
          { id: "cl3", nombre: "Genvamex", logo_url: "/clients/genvamex.svg" },
          { id: "cl4", nombre: "Grupo Geyser", logo_url: "/clients/geyser.svg" },
          { id: "cl5", nombre: "Howmet Aerospace", logo_url: "/clients/howmet.svg" },
          { id: "cl6", nombre: "Vertiv", logo_url: "/clients/vertiv.svg" },
          { id: "cl7", nombre: "Plastiexports", logo_url: "/clients/plastiexports.svg" },
          { id: "cl8", nombre: "Sanilock", logo_url: "/clients/sanilock.svg" },
        ],
    testimonios: Array.isArray(r.testimonios) ? r.testimonios as SiteContent["testimonios"] : [
      { id: "te1", nombre: "Ing. Carlos Mendoza", cargo: "Coordinador de Manufactura", empresa: "Vertiv", texto: "JACO entendió a la perfección nuestros requerimientos técnicos. Entregaron piezas con tolerancias exactas y tiempos competitivos. Son nuestro proveedor de confianza para fixtures críticos." },
      { id: "te2", nombre: "Lic. Mariana Treviño", cargo: "Compras Industriales", empresa: "Grupo Geyser", texto: "La capacidad de JACO de fabricar desde una sola pieza nos salvó en varios proyectos urgentes. Su flexibilidad y calidad son raras en la industria." },
      { id: "te3", nombre: "Ing. Roberto Garza", cargo: "Gerente de Operaciones", empresa: "Plastiexports", texto: "Llevamos más de 5 años trabajando con JACO. Han crecido con nosotros y siempre encuentran la solución técnica adecuada. Recomendado al 100%." },
    ],
    faq: Array.isArray(r.faq) ? r.faq as SiteContent["faq"] : [
      { id: "f1", pregunta: "¿Cuál es el pedido mínimo?", respuesta: "No hay mínimo de producción. Fabricamos desde una sola pieza con la misma calidad que en una corrida de producción." },
      { id: "f2", pregunta: "¿Qué materiales trabajan?", respuesta: "Aluminio, acero inoxidable (304, 316L sanitario), acero al carbón, bronce, latón, plásticos técnicos (POM, nylon, UHMW) y materiales endurecidos vía EDM." },
      { id: "f3", pregunta: "¿Cuál es el tiempo de entrega típico?", respuesta: "Cotización en 24–48 horas. Fabricación entre 5 y 20 días hábiles dependiendo de complejidad y volumen. Servicio express disponible." },
      { id: "f4", pregunta: "¿Tienen certificaciones?", respuesta: "Operamos bajo estándares ISO 9001 (en proceso de certificación formal) e inspección dimensional con CMM trazable. Documentamos cada lote con su reporte de control de calidad." },
      { id: "f5", pregunta: "¿Trabajan con planos del cliente o también diseñan?", respuesta: "Ambos. Si tienes planos, los recibimos en DWG, STEP, IGES, PDF o sketches. Si solo tienes una idea, nuestro equipo de Diseño CAD/CAM la convierte en plano y prototipo." },
      { id: "f6", pregunta: "¿Atienden fuera de Monterrey?", respuesta: "Sí. Enviamos a toda la República Mexicana y exportamos a Estados Unidos. Empaque industrial incluido." },
      { id: "f7", pregunta: "¿Cómo pago?", respuesta: "Aceptamos transferencia electrónica, cheque empresarial y términos de crédito previa evaluación. Facturación electrónica inmediata." },
      { id: "f8", pregunta: "¿Puedo visitar el taller?", respuesta: "Por supuesto. Agenda una visita técnica vía WhatsApp o el formulario de contacto. Estamos en Fresno 2112, Col. Moderna, Monterrey, N.L." },
    ],
    ctaBanner: {
      headline: "¿LISTO PARA TU PRÓXIMO PROYECTO?",
      description: "Cotización en 24 horas. Sin mínimos de producción. Calidad industrial garantizada.",
      cta_primary_text: "COTIZAR POR WHATSAPP",
      cta_primary_href: "https://wa.me/528114883334?text=Hola%20JACO%2C%20me%20gustar%C3%ADa%20cotizar%20un%20proyecto",
      cta_secondary_text: "ENVIAR REQUERIMIENTO",
      cta_secondary_href: "#contacto",
      ...((r.ctaBanner as object) || {}),
    },
    contacto: {
      label: "13 / CONTACTO",
      headline: "HABLEMOS DE TU PROYECTO",
      subtitle: "Cuéntanos lo que necesitas. Respondemos en menos de 24 horas hábiles.",
      phone_display: "81 1488 3334",
      phone_href: "tel:+528114883334",
      email: "contacto@maquinadosjaco.com",
      address_line1: "Fresno 2112, Col. Moderna",
      address_line2: "64530 Monterrey, N.L., México",
      hours_weekday: "Lun–Vie: 8:00 a.m. – 6:00 p.m.",
      hours_saturday: "Sáb: 9:00 a.m. – 1:00 p.m.",
      whatsapp_href: "https://wa.me/528114883334?text=Hola%20JACO%2C%20me%20gustar%C3%ADa%20cotizar%20un%20proyecto",
      whatsapp_message_default: "Hola JACO, me gustaría cotizar un proyecto",
      maps_embed_src: "https://maps.google.com/maps?q=Fresno+2112,+Moderna,+Monterrey,+Nuevo+León,+México&t=&z=15&ie=UTF8&iwloc=&output=embed",
      facebook_page_name: "JACO Diseño y Manufactura CNC",
      facebook_page_href: "#",
      ...((r.contacto as object) || {}),
    },
    footer: {
      tagline: "Diseño y manufactura CNC de precisión en Monterrey, N.L. Fabricamos desde una sola pieza, sin mínimos de producción, con calidad y tiempos de entrega garantizados.",
      nav_links: {
        title: "NAVEGACIÓN",
        items: [
          { label: "Inicio", href: "#hero" },
          { label: "Nosotros", href: "#nosotros" },
          { label: "Servicios", href: "#servicios" },
          { label: "Proceso", href: "#proceso" },
          { label: "Clientes", href: "#clientes" },
          { label: "Contacto", href: "#contacto" },
        ],
      },
      services_links: {
        title: "SERVICIOS",
        items: [
          { label: "Manufactura CNC", href: "#servicios" },
          { label: "Soldadura industrial", href: "#soldadura" },
          { label: "Diseño CAD/CAM", href: "#servicios" },
          { label: "Comercialización", href: "#comercializacion" },
          { label: "Renta de equipos", href: "#comercializacion" },
        ],
      },
      copyright: "© 2026 Maquinados JACO. Todos los derechos reservados.",
      designer_text: "Diseñado por Mario Vidaña",
      social_facebook: "#",
      social_instagram: "#",
      social_linkedin: "#",
      ...((r.footer as object) || {}),
    },
  };
}
